run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - cyclop
    - dupl
    - durationcheck
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - tenv
    - testableexamples
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - wrapcheck

linters-settings:
  cyclop:
    max-complexity: 15
  
  funlen:
    lines: 80
    statements: 40
  
  gocognit:
    min-complexity: 15
  
  gocyclo:
    min-complexity: 15
  
  godox:
    keywords:
      - NOTE
      - OPTIMIZE
      - HACK
  
  govet:
    check-shadowing: true
  
  lll:
    line-length: 120
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - gocognit
        - cyclop
        - lll
        - goconst
        - wrapcheck
        - gochecknoglobals
        - goerr113
    
    # Exclude linters for main.go files
    - path: cmd/
      linters:
        - gochecknoinits
        - gochecknoglobals
    
    # Exclude specific rules for generated files
    - path: ".*\\.pb\\.go"
      linters:
        - lll
        - goconst
    
    # Allow long lines in comments
    - source: "^//.*"
      linters:
        - lll

  max-issues-per-linter: 0
  max-same-issues: 0