version: "2"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - goimports
    - misspell
  disable-all: true

linters-settings:
  misspell:
    locale: US

issues:
  max-issues-per-linter: 0
  max-same-issues: 0